# Generated by Django 5.2.5 on 2025-08-16 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='servings',
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_per_serving', models.PositiveIntegerField(blank=True, help_text='Calories per serving', null=True)),
                ('protein_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbs_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fat_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fiber_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sugar_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='meals.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField(help_text='List of ingredients')),
                ('instructions', models.TextField(help_text='Cooking instructions')),
                ('prep_time', models.PositiveIntegerField(default=0, help_text='Preparation time in minutes')),
                ('cook_time', models.PositiveIntegerField(default=0, help_text='Cooking time in minutes')),
                ('servings', models.PositiveIntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='meals.meal')),
            ],
        ),
    ]
