# Generated by Django 4.2.23 on 2025-08-22 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0002_remove_meal_cook_time_remove_meal_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklymealplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklymealplan',
            name='week_number',
            field=models.PositiveIntegerField(default=None, help_text='Week number in the year (1-53)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklymealplan',
            name='year',
            field=models.PositiveIntegerField(default=None, help_text='Year of the meal plan'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='weeklymealplan',
            unique_together={('user', 'week_number')},
        ),
        migrations.RemoveField(
            model_name='weeklymealplan',
            name='week_start_date',
        ),
    ]
