# Generated by Django 4.2.23 on 2025-08-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_weeklymealplan_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch or dinner', 'Lunch or Dinner'), ('snack', 'Snack')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='mealplanentry',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch or dinner', 'Lunch or Dinner'), ('snack', 'Snack')], max_length=20),
        ),
    ]
