# Generated by Django 4.2.23 on 2025-08-22 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_meal_meal_type_alter_meal_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealplanentry',
            unique_together={('meal_plan', 'day_of_week')},
        ),
        migrations.AddField(
            model_name='mealplanentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
