# Generated by Django 4.2.23 on 2025-08-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_mealplanentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealplanentry',
            unique_together=set(),
        ),
    ]
